"""
Investigation service — the active anomaly investigation and its history.

The active investigation is generated by Sarvam AI (see sarvam_service.py)
from structured merchant context. If Sarvam is unavailable, misconfigured,
or returns something that doesn't validate, this service falls back to a
static mocked investigation — Sarvam being down must never break the
frontend.

Cognee note: `historical_notes` below comes from Cognee's per-merchant
memory (see cognee_service.py) instead of a hardcoded string — Sarvam
reasons with real context about how similar past incidents were resolved.
Cognee being unavailable never blocks an investigation: `get_merchant_memory`
falls back to a local mocked history on its own.

n8n note: once a merchant approves an investigation's recommended actions,
workflow_service.py takes over — see `get_cached_investigation` and
`add_completed_investigation` below, which it calls once a workflow
actually completes (not merely when Sarvam proposes one).

When Maithrayi wires up Supabase, `_build_investigation_context` and the
history list below become queries against the same merchant/metrics tables
backing dashboard_service.py and merchant_service.py.
"""

import logging
import uuid

from app.models.entities import InvestigationHistoryRecord, InvestigationRecord
from app.schemas.investigation import (
    ActiveInvestigation,
    ActiveInvestigationResponse,
    InvestigationHistory,
    InvestigationHistoryItem,
)
from app.schemas.memory import MerchantMemory
from app.schemas.sarvam import MerchantInvestigationContext
from app.services.cognee_service import DEFAULT_MERCHANT_ID, get_merchant_memory
from app.services.sarvam_service import SarvamServiceError, generate_investigation

logger = logging.getLogger(__name__)

# Investigations returned to the frontend, keyed by the id attached in
# get_active_investigation() — lets POST /api/workflow/run look up exactly
# which investigation a merchant is approving. In-process only: a server
# restart clears it, same as every other mock store in this codebase.
_INVESTIGATION_CACHE: dict[str, ActiveInvestigation] = {}

# Recent incidents shown on the dashboard's Investigations table — a plain
# mutable list (not a function) so add_completed_investigation can append
# to it. Newest first. `_SEED_HISTORY` is kept alongside so Demo Mode (see
# reset_demo_state below) can restore exactly this starting point.
_SEED_HISTORY: list[InvestigationHistoryRecord] = [
    InvestigationHistoryRecord(incident="Revenue Drop", severity="High", status="Investigating", time_label="09:42 AM"),
    InvestigationHistoryRecord(incident="Refund Spike", severity="Medium", status="Resolved", time_label="Yesterday"),
    InvestigationHistoryRecord(incident="QR Offline", severity="High", status="Resolved", time_label="Friday"),
    InvestigationHistoryRecord(incident="Payment Delay", severity="Low", status="Verified", time_label="Last Week"),
]
_HISTORY: list[InvestigationHistoryRecord] = list(_SEED_HISTORY)


def _format_memory_summary(memories: list[MerchantMemory]) -> str:
    if not memories:
        return "No prior incidents on record for this merchant."

    lines = [
        f"- {m.incident_date}: {m.root_cause} Verification: {m.verification_result}"
        for m in memories[:3]
    ]
    return "Previous incidents:\n" + "\n".join(lines)


async def _build_investigation_context() -> MerchantInvestigationContext:
    # Mirrors the mock data in dashboard_service.py / merchant_service.py —
    # once Supabase is wired up, all three will read from the same tables.
    memories = await get_merchant_memory(DEFAULT_MERCHANT_ID)

    return MerchantInvestigationContext(
        merchant_name="Kavita General Store",
        merchant_category="Grocery & Daily Essentials",
        revenue_today=18450,
        revenue_change_percent=-24,
        payment_success_rate=96.2,
        refund_count=17,
        transaction_count=1842,
        upi_status="Operational",
        qr_status="Operational",
        historical_notes=_format_memory_summary(memories),
    )


def _get_fallback_record() -> InvestigationRecord:
    return InvestigationRecord(
        id="inv_revenue_drop_fallback",
        anomaly_title="Revenue anomaly detected",
        summary=(
            "Revenue dropped sharply this evening alongside a spike in payment "
            "failures and refunds."
        ),
        confidence=91,
        root_cause="Payment processing disruption.",
        evidence=[
            "Payment success decreased.",
            "Refunds increased.",
            "Transactions dropped during evening hours.",
        ],
        recommended_actions=[
            "Approve the recovery workflow to retry failed transactions.",
            "Notify affected customers of the resolved delay.",
        ],
        verification_checks=[
            "Payment success rate returns above 95%.",
            "Refund count returns to baseline within 24 hours.",
        ],
        merchant_message=(
            "We noticed a dip in your evening sales and are already on it — "
            "approve the fix below to recover affected transactions."
        ),
        workflow_status="Awaiting merchant approval",
    )


async def get_active_investigation() -> ActiveInvestigationResponse:
    context = await _build_investigation_context()

    try:
        result = await generate_investigation(context)
    except SarvamServiceError as exc:
        logger.warning("Falling back to the mocked investigation: %s", exc)
        record = _get_fallback_record()
        result = ActiveInvestigation(
            anomaly_title=record.anomaly_title,
            summary=record.summary,
            confidence=record.confidence,
            root_cause=record.root_cause,
            evidence=record.evidence,
            recommended_actions=record.recommended_actions,
            verification_checks=record.verification_checks,
            merchant_message=record.merchant_message,
            workflow_status=record.workflow_status,
        )

    investigation_id = f"inv_{uuid.uuid4().hex[:10]}"
    _INVESTIGATION_CACHE[investigation_id] = result

    return ActiveInvestigationResponse(investigation_id=investigation_id, **result.model_dump())


def get_cached_investigation(investigation_id: str) -> ActiveInvestigation | None:
    """Look up an investigation previously returned by get_active_investigation()
    — used by workflow_service.py when a merchant approves it."""
    return _INVESTIGATION_CACHE.get(investigation_id)


def add_completed_investigation(incident: str, time_label: str) -> None:
    """Append a newly-completed incident to the top of the history list.

    Called by workflow_service.py once a recovery workflow actually
    completes and is verified — not when Sarvam merely proposes one. See
    the n8n note in this module's docstring.
    """
    _HISTORY.insert(
        0,
        InvestigationHistoryRecord(
            incident=incident, severity="Medium", status="Resolved", time_label=time_label
        ),
    )


def reset_demo_state() -> None:
    """Demo Mode: restore the investigation history and clear the
    investigation cache back to a clean starting point. See
    routes/demo.py — this guarantees a repeatable demo run."""
    _HISTORY[:] = list(_SEED_HISTORY)
    _INVESTIGATION_CACHE.clear()


async def get_investigation_history() -> InvestigationHistory:
    return InvestigationHistory(
        items=[
            InvestigationHistoryItem(
                incident=r.incident,
                severity=r.severity,  # type: ignore[arg-type]
                status=r.status,  # type: ignore[arg-type]
                time_label=r.time_label,
            )
            for r in _HISTORY
        ]
    )
